variable "gcp_project_id" {}
variable "name" {}
variable "name2" {}
variable "gcp_region" {}
variable "gcp_zone" {}
variable "machine" {}
variable "image" {}
variable "license_file" {}
variable "license_file2" {}
variable "ubuntu_image" {}
# vpc module
variable "vpcs" {}
# subnet module
variable "subnets" {}
variable "subnet_cidrs" {}
#####
variable "juice_shop_image_name" {}
variable "juice_shop_machine" {}
variable "juice-ip" {}
variable "trust-ip" {}
variable "trust-ip2" {}